name = "ldsg-cloud"
main = "src/index.js"
compatibility_date = "2025-09-01"

[[d1_databases]]
binding = "DB"
database_name = "ldsg"
database_id = "00000000-0000-0000-0000-000000000000"

[[r2_buckets]]
binding = "FILES"
bucket_name = "ldsg-files"
